version: '3.7'

services:
  postgres:
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=reality
      - POSTGRES_DB=reality
      - POSTGRES_PASSWORD=reality
    volumes:
      - realitydata:/var/lib/postgresql/data

  redis:
    image: redis:4-alpine
    ports:
      - "6379:6379"
  celery_worker:
    build: .
    command: celery -A reality_worker worker -l INFO --max-tasks-per-child 1
    volumes:
      - .:/code
    depends_on:
      - redis
    environment:
      - WORKER_REDIS_URL=redis://redis:6379/0
      - SCRAPY_SETTINGS_MODULE=reality_scrapy.reality_scrapy.settings

volumes:
  realitydata:
