# Generated by Django 2.2.8 on 2020-01-05 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RealityPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('image_url', models.URLField()),
                ('link_url', models.URLField()),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('size', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
