# Generated by Django 2.2.8 on 2020-01-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RealityPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('source', models.TextField()),
                ('image_url', models.URLField(default=None, null=True)),
                ('link_url', models.URLField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('size', models.IntegerField()),
                ('date_updated', models.DateTimeField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
